fastlane_version "1.57.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new daily build to TestFlight"
  desc "A daily build is sent to Guava team by default"
  lane :development do |options|
    config_env(options)
    prepare(remote_branch: options[:remote_branch])
    increment_build_number
    match(type: "adhoc")
    gym(scheme: "Guava") # Build your app - more options available
    pilot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    #match(type: "appstore") # more information: https://codesigning.guide
    snapshot
    cert
    sigh
    gym(scheme: "Guava") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    match(type: "appstore")
    snapshot
    gym(scheme: "Guava") # Build your app - more options available
    deliver(force: true)
  end

# PRIVATE LANES

    private_lane :config_env do |options|
        # Select proper xcode tool
        xcode = options[:xcode_select]
    end

    private_lane :prepare do |options|
        ensure_git_status_clean
        current_branch = git_branch

        # # Checkout remote branch if needed
        if !options[:remote_branch].nil? && options[:remote_branch] != current_branch
            puts "Checkout new branch #{options[:remote_branch]}"
            git_checkout(remote_branch: options[:remote_branch])
        else
            git_pull
        end
    end

  after_all do |lane|
    # This block is called, only if the executed lane was successful


  end

  error do |lane, exception|

  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
